export default{async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{headers:cors()});try{if(url.pathname.startsWith("/api/"))return api(request,env,url);let p=url.pathname;if(p.endsWith("/"))p+="index.html";if(!p.includes(".")&&p!=="/")p+="/index.html";let u=new URL(request.url);u.pathname=p;let r=await env.ASSETS.fetch(new Request(u,request));if(r.status!==404)return r;u.pathname="/index.html";return env.ASSETS.fetch(new Request(u,request))}catch(e){return json({ok:false,error:e.message},e.status||500)}}}
async function api(req,env,url){let parts=url.pathname.replace(/^\/api\/?/,"").split("/").filter(Boolean),admin=parts[0]==="admin";if(admin)auth(req,env);if(admin&&parts[1]==="diagnostics")return json({ok:true,hasAdminToken:!!env.ADMIN_TOKEN,hasR2Bucket:hasBucket(env),hasPublicR2BaseUrl:!!env.PUBLIC_R2_BASE_URL});if(parts[0]==="content")return getContent(env,safe(parts[1]||"site-content"));if(admin&&parts[1]==="content"){let k=safe(parts[2]||"site-content");if(req.method==="GET")return getContent(env,k);if(req.method==="PUT")return putContent(req,env,k)}if(admin&&parts[1]==="media"&&req.method==="POST")return upload(req,env);return json({ok:false,error:"Rota não encontrada"},404)}
function hasBucket(env){return !!(env.R2_BUCKET||env.CONNECTPIXEL_R2||env.MEDIA_BUCKET)}
function bucket(env){let b=env.R2_BUCKET||env.CONNECTPIXEL_R2||env.MEDIA_BUCKET;if(!b)throw new E("R2_BUCKET não configurado em Settings > Bindings. O painel carrega, mas não salva sem o R2.",500);return b}
async function assetFallback(env,k){let u=new URL("https://x/content/"+k+".json");let f=await env.ASSETS.fetch(new Request(u));if(f.ok)return new Response(await f.text(),{headers:{"Content-Type":"application/json; charset=utf-8",...cors()}});return json({meta:{fallback:true},site:{},bio:{}})}
async function getContent(env,k){if(hasBucket(env)){let obj=await bucket(env).get(`content/${k}.json`);if(obj)return new Response(await obj.text(),{headers:{"Content-Type":"application/json; charset=utf-8",...cors()}})}return assetFallback(env,k)}
async function putContent(req,env,k){let body=await req.text();JSON.parse(body);await bucket(env).put(`content/${k}.json`,body,{httpMetadata:{contentType:"application/json; charset=utf-8"}});return json({ok:true,key:k,savedAt:new Date().toISOString()})}
async function upload(req,env){let form=await req.formData(),file=form.get("file");if(!file||typeof file==="string")return json({ok:false,error:"Arquivo obrigatório"},400);let folder=clean(String(form.get("folder")||"uploads")),name=clean(String(form.get("name")||file.name.replace(/\.[^.]+$/,""))),ext=(file.name.match(/\.[a-z0-9]+$/i)||[""])[0].toLowerCase(),key=`media/${folder}/${new Date().toISOString().slice(0,10)}/${name}-${crypto.randomUUID()}${ext}`;await bucket(env).put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});let base=(env.PUBLIC_R2_BASE_URL||"").replace(/\/$/,"");return json({ok:true,key,url:base?base+"/"+key:key})}
function auth(req,env){if(!env.ADMIN_TOKEN)throw new E("ADMIN_TOKEN não configurado em Settings > Variables and Secrets.",500);if((req.headers.get("Authorization")||"")!==`Bearer ${env.ADMIN_TOKEN}`)throw new E("Não autorizado.",401)}
function safe(k){if(!/^[a-z0-9_-]+$/i.test(k))throw new E("Chave inválida.",400);return k}
function clean(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)||"arquivo"}
function json(d,status=200){return new Response(JSON.stringify(d,null,2),{status,headers:{"Content-Type":"application/json; charset=utf-8",...cors()}})}
function cors(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,PUT,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization"}}
class E extends Error{constructor(m,s){super(m);this.status=s}}